# https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository
patreon: DietPi
custom: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6DVBECXRW3TAA